const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');
const { logger } = require('../utils/logger');

// ── Color Palette ──────────────────────────────────────────────
const COLORS = {
  primary: '#4F46E5',       // Indigo
  primaryDark: '#3730A3',
  accent: '#7C3AED',        // Violet
  text: '#1E1B4B',          // Deep navy
  textSecondary: '#6B7280',
  textLight: '#9CA3AF',
  background: '#F8F7FF',
  white: '#FFFFFF',
  codeBg: '#1E1B4B',
  codeText: '#A5F3FC',
  keyPointBullet: '#4F46E5',
  divider: '#E5E7EB',
  coverBg1: '#1E1B4B',
  coverBg2: '#312E81',
  tagBg: '#EEF2FF',
  tagText: '#4338CA',
  successGreen: '#10B981',
  warningYellow: '#F59E0B',
};

const PAGE_WIDTH = 595.28;  // A4
const PAGE_HEIGHT = 841.89;
const MARGIN = 50;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;

// ── Fonts (using built-in PDFKit fonts) ───────────────────────
const FONTS = {
  regular: 'Helvetica',
  bold: 'Helvetica-Bold',
  oblique: 'Helvetica-Oblique',
  boldOblique: 'Helvetica-BoldOblique',
  mono: 'Courier',
  monoBold: 'Courier-Bold',
};

/**
 * Draw a filled rectangle.
 */
function fillRect(doc, x, y, w, h, color) {
  doc.save().rect(x, y, w, h).fill(color).restore();
}

/**
 * Draw a horizontal rule line.
 */
function drawHRule(doc, y, color = COLORS.divider, width = CONTENT_WIDTH) {
  doc.save().moveTo(MARGIN, y).lineTo(MARGIN + width, y).lineWidth(0.5).strokeColor(color).stroke().restore();
}

/**
 * Add a new page and reset Y position tracking.
 */
function addPage(doc) {
  doc.addPage();
  return MARGIN + 20;
}

/**
 * Draw the cover page.
 */
function drawCover(doc, { title, channel, videoUrl, language, thumbnail }) {
  // Background gradient (simulated with two rects)
  fillRect(doc, 0, 0, PAGE_WIDTH, PAGE_HEIGHT * 0.7, COLORS.coverBg1);
  fillRect(doc, 0, PAGE_HEIGHT * 0.7, PAGE_WIDTH, PAGE_HEIGHT * 0.3, COLORS.background);

  // Decorative circles
  doc.save().circle(PAGE_WIDTH - 50, 80, 120).fillOpacity(0.05).fill(COLORS.white).restore();
  doc.save().circle(50, PAGE_HEIGHT * 0.6, 80).fillOpacity(0.04).fill(COLORS.white).restore();

  // Logo / Brand tag
  const tagW = 160;
  const tagH = 28;
  const tagX = (PAGE_WIDTH - tagW) / 2;
  fillRect(doc, tagX, 50, tagW, tagH, COLORS.accent);
  doc.font(FONTS.bold).fontSize(11).fillColor(COLORS.white)
    .text('VIDEO2PDF AI', tagX, 57, { width: tagW, align: 'center' });

  // Title
  doc.font(FONTS.bold)
    .fontSize(title.length > 40 ? 26 : 32)
    .fillColor(COLORS.white)
    .text(title, MARGIN, 120, { width: CONTENT_WIDTH, align: 'center' });

  // Channel
  const titleY = doc.y + 16;
  doc.font(FONTS.regular).fontSize(14).fillColor('#A5B4FC')
    .text(channel ? `by ${channel}` : '', MARGIN, titleY, { width: CONTENT_WIDTH, align: 'center' });

  // Language badge
  const langY = doc.y + 20;
  const langW = 110;
  const langX = (PAGE_WIDTH - langW) / 2;
  fillRect(doc, langX, langY, langW, 26, COLORS.primary);
  doc.font(FONTS.bold).fontSize(10).fillColor(COLORS.white)
    .text(language.toUpperCase(), langX, langY + 7, { width: langW, align: 'center' });

  // Divider line
  const divY = langY + 55;
  doc.save().moveTo(MARGIN + 80, divY).lineTo(PAGE_WIDTH - MARGIN - 80, divY)
    .lineWidth(1).strokeColor('#4338CA').stroke().restore();

  // Info section (white card at bottom)
  const cardY = PAGE_HEIGHT * 0.7 - 10;
  fillRect(doc, MARGIN, cardY, CONTENT_WIDTH, 90, COLORS.white);
  doc.save().rect(MARGIN, cardY, CONTENT_WIDTH, 90).lineWidth(1).strokeColor(COLORS.divider).stroke().restore();

  doc.font(FONTS.bold).fontSize(10).fillColor(COLORS.primary)
    .text('GENERATED BY VIDEO2PDF AI', MARGIN + 16, cardY + 14);
  doc.font(FONTS.regular).fontSize(9).fillColor(COLORS.textSecondary)
    .text('AI-Powered YouTube Tutorial to Structured PDF Learning System', MARGIN + 16, cardY + 28);

  // URL
  if (videoUrl) {
    doc.font(FONTS.regular).fontSize(8).fillColor(COLORS.textLight)
      .text(`Source: ${videoUrl}`, MARGIN + 16, cardY + 44);
  }

  // Generated date
  const dateStr = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  doc.font(FONTS.regular).fontSize(8).fillColor(COLORS.textLight)
    .text(`Generated: ${dateStr}`, MARGIN + 16, cardY + 58);

  // Bottom watermark
  doc.font(FONTS.regular).fontSize(8).fillColor(COLORS.textLight)
    .text('For educational purposes only.', MARGIN, PAGE_HEIGHT - 30, { width: CONTENT_WIDTH, align: 'center' });
}

/**
 * Draw a section header with colored background band.
 */
function drawSectionHeader(doc, text, y, options = {}) {
  const { color = COLORS.primary, fontSize = 16, icon } = options;
  const headerH = 36;

  // Left accent bar
  fillRect(doc, MARGIN, y, 4, headerH, color);
  // Light background
  fillRect(doc, MARGIN + 4, y, CONTENT_WIDTH - 4, headerH, COLORS.tagBg);

  const label = icon ? `${icon}  ${text}` : text;
  doc.font(FONTS.bold).fontSize(fontSize).fillColor(color)
    .text(label, MARGIN + 16, y + (headerH - fontSize) / 2 + 2, { width: CONTENT_WIDTH - 20 });

  return y + headerH + 10;
}

/**
 * Draw chapter title.
 */
function drawChapterTitle(doc, chapterNumber, title, y) {
  const headerH = 48;
  // Gradient-like background
  fillRect(doc, MARGIN, y, CONTENT_WIDTH, headerH, COLORS.primary);
  doc.save().circle(MARGIN + CONTENT_WIDTH - 30, y + headerH / 2, 30).fillOpacity(0.1).fill(COLORS.white).restore();

  // Chapter number badge
  doc.font(FONTS.bold).fontSize(10).fillColor('#A5B4FC')
    .text(`CHAPTER ${chapterNumber}`, MARGIN + 14, y + 8, { width: 200 });

  doc.font(FONTS.bold).fontSize(16).fillColor(COLORS.white)
    .text(title, MARGIN + 14, y + 22, { width: CONTENT_WIDTH - 28 });

  return y + headerH + 14;
}

/**
 * Draw key points list.
 */
function drawKeyPoints(doc, keyPoints, y) {
  if (!keyPoints || keyPoints.length === 0) return y;

  y = drawSectionHeader(doc, 'Key Points', y, { icon: '★', fontSize: 13 });

  for (const point of keyPoints) {
    if (doc.y > PAGE_HEIGHT - MARGIN - 80) {
      doc.addPage();
      y = MARGIN + 20;
    }

    // Bullet
    doc.save().circle(MARGIN + 10, y + 7, 4).fill(COLORS.primary).restore();

    doc.font(FONTS.regular).fontSize(11).fillColor(COLORS.text)
      .text(point, MARGIN + 22, y, { width: CONTENT_WIDTH - 22 });

    y = doc.y + 6;
  }

  return y + 10;
}

/**
 * Draw code example block.
 */
function drawCodeBlock(doc, example, y) {
  if (!example.code || !example.code.trim()) return y;

  // Code block header
  const headerH = 24;
  fillRect(doc, MARGIN, y, CONTENT_WIDTH, headerH, COLORS.codeBg);
  const langLabel = example.language && example.language !== 'text' ? example.language.toUpperCase() : 'CODE';
  doc.font(FONTS.monoBold).fontSize(9).fillColor('#A5B4FC')
    .text(langLabel, MARGIN + 10, y + 7, { width: 80 });
  doc.font(FONTS.mono).fontSize(9).fillColor('#6B7280')
    .text('■ ■ ■', MARGIN + CONTENT_WIDTH - 50, y + 7);

  y += headerH;

  // Code body
  const codeLines = example.code.trim().split('\n');
  const lineHeight = 14;
  const codeH = codeLines.length * lineHeight + 16;

  fillRect(doc, MARGIN, y, CONTENT_WIDTH, codeH, '#13111F');
  doc.font(FONTS.mono).fontSize(9).fillColor(COLORS.codeText)
    .text(example.code.trim(), MARGIN + 12, y + 8, {
      width: CONTENT_WIDTH - 24,
      lineGap: 2,
    });

  y += codeH;

  // Explanation below code
  if (example.explanation) {
    y += 6;
    doc.font(FONTS.oblique).fontSize(10).fillColor(COLORS.textSecondary)
      .text(`↑ ${example.explanation}`, MARGIN, y, { width: CONTENT_WIDTH });
    y = doc.y + 6;
  }

  return y + 8;
}

/**
 * Draw Table of Contents.
 */
function drawTableOfContents(doc, chapters, hasQuiz, hasInterviewQs) {
  doc.addPage();
  let y = MARGIN + 10;

  // TOC Header
  fillRect(doc, 0, 0, PAGE_WIDTH, 80, COLORS.primary);
  doc.font(FONTS.bold).fontSize(22).fillColor(COLORS.white)
    .text('TABLE OF CONTENTS', MARGIN, 26, { width: CONTENT_WIDTH });

  y = 100;

  const items = [
    { label: 'Introduction', page: 3 },
    ...chapters.map((ch, i) => ({ label: ch.title, page: 4 + i })),
  ];

  if (hasInterviewQs) items.push({ label: 'Interview Questions', page: 4 + chapters.length });
  if (hasQuiz) items.push({ label: 'Quiz / Practice Questions', page: 4 + chapters.length + 1 });

  items.forEach((item, idx) => {
    const isEven = idx % 2 === 0;
    if (isEven) fillRect(doc, MARGIN, y, CONTENT_WIDTH, 28, COLORS.tagBg);

    // Number badge
    fillRect(doc, MARGIN + 4, y + 4, 22, 20, COLORS.primary);
    doc.font(FONTS.bold).fontSize(10).fillColor(COLORS.white)
      .text(String(idx + 1), MARGIN + 4, y + 8, { width: 22, align: 'center' });

    // Chapter title
    doc.font(FONTS.regular).fontSize(12).fillColor(COLORS.text)
      .text(item.label, MARGIN + 34, y + 8, { width: CONTENT_WIDTH - 80 });

    // Dotted line + page number
    doc.font(FONTS.regular).fontSize(10).fillColor(COLORS.textLight)
      .text(`${item.page}`, MARGIN + CONTENT_WIDTH - 20, y + 9, { width: 20, align: 'right' });

    y += 28;
  });
}

/**
 * Draw interview questions section.
 */
function drawInterviewQuestions(doc, questions) {
  doc.addPage();
  let y = MARGIN + 10;

  fillRect(doc, 0, 0, PAGE_WIDTH, 70, COLORS.primaryDark);
  doc.font(FONTS.bold).fontSize(20).fillColor(COLORS.white)
    .text('INTERVIEW QUESTIONS', MARGIN, 22, { width: CONTENT_WIDTH });

  y = 90;

  questions.forEach((item, i) => {
    if (y > PAGE_HEIGHT - MARGIN - 100) {
      doc.addPage();
      y = MARGIN + 20;
    }

    // Question number + bubble
    fillRect(doc, MARGIN, y, CONTENT_WIDTH, 30, COLORS.primary);
    doc.font(FONTS.bold).fontSize(10).fillColor('#A5B4FC')
      .text(`Q${i + 1}`, MARGIN + 10, y + 9, { width: 30 });
    doc.font(FONTS.bold).fontSize(11).fillColor(COLORS.white)
      .text(item.question, MARGIN + 36, y + 9, { width: CONTENT_WIDTH - 46 });

    y += 36;

    // Answer
    fillRect(doc, MARGIN, y, 3, 0, COLORS.successGreen); // will be overridden
    doc.font(FONTS.regular).fontSize(11).fillColor(COLORS.text)
      .text(item.answer, MARGIN + 14, y + 4, { width: CONTENT_WIDTH - 14 });

    y = doc.y + 16;
    drawHRule(doc, y - 6);
  });
}

/**
 * Draw MCQ / Quiz section.
 */
function drawQuiz(doc, mcqs) {
  doc.addPage();
  let y = MARGIN + 10;

  fillRect(doc, 0, 0, PAGE_WIDTH, 70, COLORS.accent);
  doc.font(FONTS.bold).fontSize(20).fillColor(COLORS.white)
    .text('PRACTICE QUIZ', MARGIN, 22, { width: CONTENT_WIDTH });

  y = 90;

  const optionLabels = ['A', 'B', 'C', 'D'];

  mcqs.forEach((mcq, i) => {
    if (y > PAGE_HEIGHT - MARGIN - 150) {
      doc.addPage();
      y = MARGIN + 20;
    }

    // Question
    fillRect(doc, MARGIN, y, CONTENT_WIDTH, 30, COLORS.tagBg);
    doc.font(FONTS.bold).fontSize(11).fillColor(COLORS.primary)
      .text(`${i + 1}. ${mcq.question}`, MARGIN + 10, y + 8, { width: CONTENT_WIDTH - 20 });

    y += 34;

    // Options
    (mcq.options || []).forEach((opt, optIdx) => {
      const isCorrect = optIdx === mcq.correctIndex;
      const bgColor = isCorrect ? '#D1FAE5' : COLORS.white;
      const textColor = isCorrect ? '#065F46' : COLORS.text;
      const borderColor = isCorrect ? COLORS.successGreen : COLORS.divider;

      fillRect(doc, MARGIN + 10, y, CONTENT_WIDTH - 10, 22, bgColor);
      doc.save().rect(MARGIN + 10, y, CONTENT_WIDTH - 10, 22).lineWidth(0.5).strokeColor(borderColor).stroke().restore();

      // Option letter badge
      fillRect(doc, MARGIN + 10, y, 22, 22, isCorrect ? COLORS.successGreen : COLORS.textLight);
      doc.font(FONTS.bold).fontSize(9).fillColor(COLORS.white)
        .text(optionLabels[optIdx], MARGIN + 10, y + 6, { width: 22, align: 'center' });

      doc.font(isCorrect ? FONTS.bold : FONTS.regular).fontSize(10).fillColor(textColor)
        .text(opt, MARGIN + 38, y + 5, { width: CONTENT_WIDTH - 48 });

      y += 24;
    });

    // Explanation
    if (mcq.explanation) {
      y += 4;
      fillRect(doc, MARGIN + 10, y, CONTENT_WIDTH - 10, 22, '#FEF3C7');
      doc.font(FONTS.oblique).fontSize(9).fillColor('#92400E')
        .text(`💡 ${mcq.explanation}`, MARGIN + 16, y + 6, { width: CONTENT_WIDTH - 26 });
      y += 26;
    }

    y += 10;
  });
}

/**
 * Main PDF generation function.
 * @param {Object} documentData - Structured JSON from AI pipeline
 * @param {Object} metadata - { videoId, title, channel, videoUrl, language }
 * @param {Object} options - { includeQuiz, includeInterviewQuestions, includeExamples, includeKeyPoints }
 * @param {string} outputPath - Full path to save the PDF
 */
async function generatePDF(documentData, metadata, options, outputPath) {
  return new Promise((resolve, reject) => {
    try {
      logger.info(`Generating PDF: ${outputPath}`);

      // Ensure output directory exists
      const dir = path.dirname(outputPath);
      if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
      }

      const doc = new PDFDocument({
        size: 'A4',
        margins: { top: MARGIN, bottom: MARGIN, left: MARGIN, right: MARGIN },
        info: {
          Title: documentData.title,
          Author: 'Video2PDF AI',
          Subject: `Educational notes generated from YouTube tutorial`,
          Keywords: 'education, tutorial, notes, AI',
        },
      });

      const stream = fs.createWriteStream(outputPath);
      doc.pipe(stream);

      // ── Page 1: Cover ──────────────────────────────────────
      drawCover(doc, {
        title: documentData.title,
        channel: metadata.channel,
        videoUrl: metadata.url || metadata.videoUrl,
        language: documentData.language,
      });

      // ── Page 2: Table of Contents ──────────────────────────
      drawTableOfContents(
        doc,
        documentData.chapters,
        options.includeQuiz && documentData.mcqs?.length > 0,
        options.includeInterviewQuestions && documentData.interviewQuestions?.length > 0
      );

      // ── Page 3: Introduction ───────────────────────────────
      doc.addPage();
      fillRect(doc, 0, 0, PAGE_WIDTH, 70, COLORS.primary);
      doc.font(FONTS.bold).fontSize(22).fillColor(COLORS.white)
        .text('INTRODUCTION', MARGIN, 22, { width: CONTENT_WIDTH });

      let y = 90;
      if (documentData.introduction) {
        doc.font(FONTS.regular).fontSize(12).fillColor(COLORS.text)
          .text(documentData.introduction, MARGIN, y, { width: CONTENT_WIDTH, lineGap: 4 });
        y = doc.y + 20;
      }

      // Video info card
      fillRect(doc, MARGIN, y, CONTENT_WIDTH, 60, COLORS.tagBg);
      doc.save().rect(MARGIN, y, CONTENT_WIDTH, 60).lineWidth(1).strokeColor(COLORS.divider).stroke().restore();

      doc.font(FONTS.bold).fontSize(10).fillColor(COLORS.primary).text('SOURCE VIDEO', MARGIN + 14, y + 10);
      doc.font(FONTS.regular).fontSize(11).fillColor(COLORS.text).text(documentData.title, MARGIN + 14, y + 24);
      if (metadata.channel) {
        doc.font(FONTS.regular).fontSize(9).fillColor(COLORS.textSecondary).text(`Channel: ${metadata.channel}`, MARGIN + 14, y + 40);
      }
      if (metadata.url) {
        doc.font(FONTS.regular).fontSize(8).fillColor(COLORS.textLight).text(metadata.url, MARGIN + CONTENT_WIDTH * 0.4, y + 40, { width: CONTENT_WIDTH * 0.55 });
      }

      // ── Pages 4+: Chapters ─────────────────────────────────
      documentData.chapters.forEach((chapter, idx) => {
        doc.addPage();
        let cy = MARGIN + 10;

        cy = drawChapterTitle(doc, idx + 1, chapter.title, cy);

        // Summary
        if (options.includeSummary !== false && chapter.summary) {
          cy = drawSectionHeader(doc, 'Summary', cy, { icon: '◉', fontSize: 13 });
          doc.font(FONTS.regular).fontSize(11).fillColor(COLORS.text)
            .text(chapter.summary, MARGIN, cy, { width: CONTENT_WIDTH, lineGap: 3 });
          cy = doc.y + 14;
        }

        // Key Points
        if (options.includeKeyPoints !== false && chapter.keyPoints?.length > 0) {
          cy = drawKeyPoints(doc, chapter.keyPoints, cy);
        }

        // Examples
        if (options.includeExamples !== false && chapter.examples?.length > 0) {
          cy = drawSectionHeader(doc, 'Examples', cy, { icon: '⬡', fontSize: 13 });
          for (const example of chapter.examples) {
            if (cy > PAGE_HEIGHT - MARGIN - 120) {
              doc.addPage();
              cy = MARGIN + 20;
            }
            cy = drawCodeBlock(doc, example, cy);
          }
        }
      });

      // ── Interview Questions ────────────────────────────────
      if (options.includeInterviewQuestions && documentData.interviewQuestions?.length > 0) {
        drawInterviewQuestions(doc, documentData.interviewQuestions);
      }

      // ── Quiz / MCQs ────────────────────────────────────────
      if (options.includeQuiz && documentData.mcqs?.length > 0) {
        drawQuiz(doc, documentData.mcqs);
      }

      // ── Last Page: Footer ──────────────────────────────────
      doc.addPage();
      fillRect(doc, 0, 0, PAGE_WIDTH, PAGE_HEIGHT, COLORS.primary);
      doc.save().circle(PAGE_WIDTH / 2, PAGE_HEIGHT / 2 - 50, 80).fillOpacity(0.05).fill(COLORS.white).restore();

      doc.font(FONTS.bold).fontSize(24).fillColor(COLORS.white)
        .text('Video2PDF AI', MARGIN, PAGE_HEIGHT / 2 - 80, { width: CONTENT_WIDTH, align: 'center' });
      doc.font(FONTS.regular).fontSize(13).fillColor('#A5B4FC')
        .text('AI-Powered Educational Content Transformation', MARGIN, PAGE_HEIGHT / 2 - 50, {
          width: CONTENT_WIDTH, align: 'center',
        });
      doc.font(FONTS.regular).fontSize(10).fillColor('#6D6BB0')
        .text('Generated for educational purposes only.', MARGIN, PAGE_HEIGHT / 2 + 10, {
          width: CONTENT_WIDTH, align: 'center',
        });
      doc.font(FONTS.regular).fontSize(9).fillColor('#6D6BB0')
        .text(`© ${new Date().getFullYear()} Video2PDF AI`, MARGIN, PAGE_HEIGHT - 60, {
          width: CONTENT_WIDTH, align: 'center',
        });

      doc.end();

      stream.on('finish', () => {
        logger.info(`PDF generated successfully: ${outputPath}`);
        resolve(outputPath);
      });

      stream.on('error', (err) => {
        logger.error(`Stream error: ${err.message}`);
        reject(err);
      });
    } catch (err) {
      logger.error(`PDF generation error: ${err.message}`);
      reject(err);
    }
  });
}

module.exports = { generatePDF };
